version: "3.6"

services:
  app:
    build: ./
    container_name: ktor-gradle-app
    volumes:
      - ./:/ktor-app
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ktor-app
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - ktor-network
networks:
  ktor-network:
    driver: bridge
